version: '3.8'
services:
  redis:
    image: redis:7.2
    ports:
      - 6379:6379

  socketio-server:
    image: kwonghung/odds-broadcast-socketio-backend:1.0.0
    build:
      context: ./socketio-backend
    ports:
      - 3005:3005
    expose:
      - 3005
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3005
      - REDIS_HOST=redis:6379
      - EXEC_JSFILE=server.js

  broadcast-service:
    image: kwonghung/odds-broadcast-socketio-backend:1.0.0
    build:
      context: ./socketio-backend
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3005
      - REDIS_HOST=redis:6379
      - EXEC_JSFILE=broadcastService.js

  next-frontend:
    image: kwonghung/odd-broadcast-nextjs-frontend:1.0.0
    build:
      context: ./nextjs-frontend
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - PORT=3000