apiVersion: skaffold/v4beta8
kind: Config

build:
  artifacts:
    - image: localhost:32000/kwonghung/odds-broadcast/nextjs-frontend
      context: nextjs-frontend
      docker:
        dockerfile: Dockerfile

    - image: localhost:32000/kwonghung/odds-broadcast/socketio-backend
      context: socketio-backend
      docker:
        dockerfile: Dockerfile
  
  insecureRegistries: ["localhost:32000"]

profiles:
  - name: microk8s
    manifests: 
      rawYaml: [
        "kubernetes/microk8s/*.yml"
      ]
    portForward:
      - resourceType: service
        resourceName: nextjs-backend-service
        namespace: default
        port: 3000
        localPort: 3000
        address: 192.168.19.130

      - resourceType: service
        resourceName: socketio-backend-service
        namespace: default
        port: 3005
        localPort: 3005
        address: 192.168.19.130

      - resourceType: service
        resourceName: nginx-service
        namespace: default
        port: 80
        localPort: 80
        address: 192.168.19.130  