apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-frontend-ingress
  labels:
    app: odds_broadcast
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /nextjs/$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /nextjs/
            pathType: Prefix
            backend:
              service:
                name: nextjs-frontend-service
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-frontend-service
  labels:
    app: odds_broadcast
spec:
  type: ClusterIP
  selector:
    app: odds_broadcast
    component: nextjs_frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: odds_broadcast
      component: nextjs_frontend
  template:
    metadata:
      labels:
        app: odds_broadcast
        component: nextjs_frontend
    spec:
      containers:
        - name: nextjs-server
          image: localhost:32000/kwonghung/odds-broadcast/nextjs-frontend
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"

