apiVersion: v1
kind: Service
metadata:
  name: socketio-backend-service
  labels:
    app: odds_broadcast
spec:
  type: ClusterIP
  selector:
    app: odds_broadcast
    component: socketio_backend
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socketio-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odds_broadcast
      component: socketio_backend
  template:
    metadata:
      labels:
        app: odds_broadcast
        component: socketio_backend
    spec:
      containers:
        - name: socketio-server
          image: localhost:32000/kwonghung/odds-broadcast/socketio-backend
          ports:
            - containerPort: 3005
          env:
            - name: NODE_ENV
              value: production
            - name: SERVER_PORT
              value: "3005"

